# Global
safe:									true
exclude:							[TODO.md, REPOSITORY.md, CNAME, Gemfile, Gemfile.lock, __tests__]
include:							[_pages, _apps, _others, _extras, _scripts]
timezone:							Europe/London

# Dependencies
markdown:							kramdown
  
# Styling
sass:
  sass_dir:						_sass
  load_paths:
                      - _sass
                      - _sass/bootstrap
                      - _sass/material
                      - _sass/custom
  style:							compressed

# Compression
compress_html:
  comments:						all
  clippings:					all
  startings:					[]
  endings:            []
  artifacts:          [" /* */ ", " /* */", "/* */ ", "/* */", "/*jshint ignore:start*/", "/*jshint ignore:end*/"]
  ignore:
    envs:             [debug]

# Permalinks
permalink:						pretty

# Setup
title:                Shelf-Dog
byline:								""
  
description:					""
url:									shelf.dog
baseurl:							/
cdn:                  https://cdnjs.cloudflare.com/ajax/libs
author:
  name:								"Shelf.dog"
  url:								https://github.com/shelf-dog

# Custom variables
version:							"0.1.0"
launched:							"2017"
fonts:								"Anonymous+Pro:400|Inconsolata:400|Roboto:400,700|Roboto+Mono:400|Fira+Mono:400|Space+Mono:400"
debug:                "debug"
performance:          "perf"
compress:             "compress"
array:                []
highlight:            "af0ad9"

# Extras
analytics:
  enable:							false
  id:									"UA-53673057-8"
  
app:
  content:            content
  namespace:          shelf_dog
  tests:              _tests